version: '2.0'
services:
  css_notes:
    image: "node_dev"
    labels:
      com.startupteam.description: "node development"
      com.startupteam.department: "node development"
      com.startupteam.release: "node for v8.0"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/root
    ports:
      - "80:10024"
    privileged: true
    networks:
      env_network:
        ipv4_address: 172.16.238.10
    ulimits:
      nproc: 65535
    hostname: css_notes
    mem_limit: 1024m
networks:
  env_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1